# Graphs (abstract data type) 

* **Vertices**
* **Edges**  
* **Cost** (e.g. Dollars, Time, Distance, etc)  

![Example Graph](http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2013/07/dg-graphs04.png)

* Examples
    * Computer networks
    * World Wide Web
    * Social networks
    * Google: PageRank
        * Looks at web as a directory  
        
        
* **Adjacency (b) List, (c) Matrix**:
![Example Matrix](http://staff.ustc.edu.cn/~csli/graduate/algorithms/book6/466_a.gif) 


* Travel Example:
    * Can you go from point A to point B? 
        * Adjacency matrix has ones for connections and zeros for no connections
![Example Travel](https://i-msdn.sec.s-msft.com/dynimg/IC8697.gif)

## Washall Algorithm  (two point connections)

In [15]:
import numpy as np

n = 4

c = np.zeros((n,n))
c[0,1] = 1
c[1,3] = 1
c[0,2] = 1
c[3,2] = 1

a = np.copy(a)

# Triple loop is woefully inefficient in python!
for k in range(0,n):
    for i in range(0,n):
        for j in range(0,n):
            if (a[i,j] == 0):
                if (a[i,k]==1) and (a[k,j] ==1):
                    a[i,j] = 1

In [18]:
print a
print c

[[ 0.  1.  1.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 0.  1.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]]


## Floyd Algorithm (for cost minimization)

**All pairs, shortest path**

In [21]:
n = 4

c = np.zeros((n,n))
c[0,1] = 1
c[1,3] = 1
c[0,2] = 1
c[3,2] = 1

a = np.copy(a)

# Triple loop is woefully inefficient in python!
for k in range(0,n):
    for i in range(0,n):
        for j in range(0,n):
            if (a[i,k] + a[k,j] < a[i,j]):
                a[i,j] = a[i,k] + a[k,j]

In [26]:
print c
print a

[[ 0.  1.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 0.  1.  1.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]]


## Using Scipy's Graph implimentation

In [34]:
from scipy.sparse import csgraph, csr_matrix

In [36]:
G_dense = np.array([[0, 2, 1],
                    [2, 0, 0],
                    [1, 0, 0]])
G_masked = np.ma.masked_values(G_dense, 0)
G_sparse = csr_matrix(G_dense)
print G_sparse

  (0, 1)	2
  (0, 2)	1
  (1, 0)	2
  (2, 0)	1


In [32]:
G2_data = np.array([[np.inf, 2,      0     ],
                    [2,      np.inf, np.inf],
                    [0,      np.inf, np.inf]])
G2_masked = np.ma.masked_invalid(G2_data)
G2_sparse = csgraph.csgraph_from_dense(G2_data, null_value=np.inf)
print G2_sparse.data

[ 2.  0.  2.  0.]
